services:
  - type: web
    name: mediaradar-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        scope: build
        sync: false
      - key: DATABASE_NAME
        value: mediaradar
      - key: GEMINI_API_KEY
        scope: build
        sync: false
      - key: ADMIN_TOKEN
        value: supersecret
      - key: CORS_ORIGINS
        value: "*"
